name: Sanity Checks Workflow

on:
  pull_request:
  push:
  # workflow_dispatch:  # manually
  # schedule:
    # - cron: "35 0 * * *"  # periodically

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv sync

      - name: Style and Typing
        uses: ./.github/actions/lint

      - name: Tests
        uses: ./.github/actions/test

      # - name: Run main function
      #   run: python -m src.main
